name: Java CI with Maven and SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 4. Build the project
      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      # 5. SonarCloud analysis (main branch push)
      - name: SonarCloud Analysis (Push)
        if: github.event_name == 'push'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=dualangalakshan002_library_system \
            -Dsonar.organization=dualangalakshan002 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN

      # 6. SonarCloud analysis (pull request)
      - name: SonarCloud Analysis (Pull Request)
        if: github.event_name == 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          PULL_REQUEST_KEY: ${{ github.event.pull_request.number }}
          PULL_REQUEST_BASE: ${{ github.base_ref }}
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=dualangalakshan002_library_system \
            -Dsonar.organization=dualangalakshan002 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.pullrequest.branch=$PULL_REQUEST_BRANCH \
            -Dsonar.pullrequest.key=$PULL_REQUEST_KEY \
            -Dsonar.pullrequest.base=$PULL_REQUEST_BASE
